/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddToTemplate: typeof import('./src/components/AddToTemplate.vue')['default']
    Callback: typeof import('./src/components/Callback.vue')['default']
    CreateNewTemplate: typeof import('./src/components/CreateNewTemplate.vue')['default']
    Done: typeof import('./src/components/Done.vue')['default']
    GettingStarted: typeof import('./src/components/GettingStarted.vue')['default']
    GettingStartedInit: typeof import('./src/components/GettingStartedInit.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    InputCalLink: typeof import('./src/components/InputCalLink.vue')['default']
    NotionLogin: typeof import('./src/components/NotionLogin.vue')['default']
    RenameCourses: typeof import('./src/components/RenameCourses.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Submit: typeof import('./src/components/Submit.vue')['default']
  }
}
